# Generated by Django 3.1.14 on 2022-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20220307_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
