# Generated by Django 3.1.14 on 2022-03-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20220308_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonElementType',
        ),
    ]
