# Generated by Django 3.1.14 on 2022-03-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_delete_pokemonelementtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='element_type',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя покемона на английском'),
        ),
    ]
