# Generated by Django 3.1.14 on 2022-03-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20220313_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя покемона на японском'),
        ),
    ]
