# Generated by Django 3.1.14 on 2022-03-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20220313_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemonentity', to='pokemon_entities.pokemon', verbose_name='Покемон'),
        ),
    ]
